### ISSUE TITLE
[Next] [Form] Improve typings of validation object

### ISSUE THREAD

**Issue by kiaking** [globalbrain/sefirot#139]
In `next` branch, we have `Form` composable which exposes `useForm`. But at the moment, typings for `Validation` object is not quite working. It would be great if we can make it work.

### How useForm works

`Form` object is used when we want to have forms with data, validation, and other utilities like reset data to its initial state. We use [Vuelidate Next](https://vuelidate-next.netlify.app) as a validation tool.

Basic usage.

```ts
interface Data {
  name: string | null
  age: number | null
}

const { data, validation } = useForm<Data>({
  data: {
    name: null,
    age: null
  },
  // This is Vuelidate validatoin rules.
  rules: {
    name: {
      required: required(),
      maxLength: maxLength(100)
    },
    age: {
      required: required(),
      maxValue: maxLength(120)
    }
  }
})
```

The validation object with the above config will have `validation.name` and `validation.age` property. However, with the current implementation, seems like `name` and `age` is not been typed and get type error saying the property don't exist.

### Expectation

- **BEST:** Both `name` and `age` is correctly typed as same as how Vuelidate types those fields.
- **BETTER:** Both `name` and `age` is defined as `any` and don't throw type error.

Because validation is quite vague anyway, I think we can live with "BETTER" option.

@brc-dd Could you take a look at this one and see if you can fix it 🤔 

The code lives at -> https://github.com/globalbrain/sefirot/blob/next/lib/composables/Form.ts

**Comment by brc-dd** [comment]
Strange enough, but TS seems to be fine with the usage:

![image](https://user-images.githubusercontent.com/40380293/191402032-077f1fba-5aaa-4bf5-a5a1-08462ce1ee7f.png)

**Comment by kiaking** [comment]
Nono, not the `Data`, we want types for `Validation` 🙌  Yes, `data.age` works, but `validation.age`, should also work 👀

**Comment by brc-dd** [comment]
Ah ok. But `validation.value.age` is right now `any`, it shouldn't throw type errors.

**Comment by kiaking** [comment]
Oh... whaaat... OK, maybe something wrong at my end...? I'll check it and close this issue if it's working 👍

**Comment by kiaking** [comment]
Confirmed it's working (as `any`). Seems like we get type error if we locally link sefirot while having `node_modules` present in sefirot 🤔
