### ISSUE TITLE
Test coverage not working 100%

### ISSUE THREAD

**Issue by kiaking** [globalbrain/sefirot#171]
Currently for some reason, test coverage misses its branch on validation rules.

`test/validation/rules/checked`

<img width="511" alt="Screen Shot 2022-12-01 at 11 34 56" src="https://user-images.githubusercontent.com/3753672/204952293-19e1d986-4f6d-4671-a31f-8eca7998b4e5.png">

It's saying that `() => msg ?? 'You must check the field.',` is not covered fully.

However, in test case, we do.

```ts
import { checked } from 'sefirot/validation/rules'

describe('validation/rules/checked', () => {
  test('it validates whether the value is true', () => {
    const rule = checked() // <- No arg
    expect(rule.$validator(undefined, null, null)).toBe(true)
    expect(rule.$validator(true, null, null)).toBe(true)
    expect(rule.$validator(false, null, null)).toBe(false)
  })

  test('it can set custome error message', () => {
    const rule = checked('Custom message.') // <- With arg
    expect(rule.$message({ $params: {} })).toBe('Custom message.')
  })
})
```

Now if we pass in `checked(undefined)`, then the coverage works as expected. So probably this is a issue on C8 side... but if there's any workaround to fix this issue, it would be cool 👀

**Comment by cuebit** [comment]
Because `rule.$validator(...)` with `const rule = checked() // <- No arg` does not evaluate the error message, therefore the branch is never reached. So you need to call `rule.$message(...)` in the same test or add another that covers the default message.

**Comment by cuebit** [comment]
I don't quite understand why it passes as 100% if you a) don't test the custom error or b) if you don't treat it as a string returning function, rather pass in the error condition as a direct value to `withMessage`. This seems odd as the function value is deemed unreachable (therefore tested). 

Furthermore, I do understand that by executing `$message()` you're adding a dependency to the branch map, so both sides of the nullish-coalescing condition should be observed... however, it's not. Which makes me think it may well be a bug.

Can't really think of another workaround other than those aforementioned or in the PR. Will keep digging, something will surface eventually.

**Comment by kiaking** [comment]
Ahhh... OK That makes sense. Well, the PR looks good and probably we should check it anyway so let's go with it!
