### ISSUE TITLE
[Table] Add flexibility to column widths

### ISSUE THREAD

**Issue by NozomuIkuta** [globalbrain/sefirot#175]
## What

- At least, let the right-most column of Table component fulfill the rest space automatically
- Or, for better design experience, let developers choose which column expand automatically (e.g. in Table component configuration)

## Why

Currently, each column is styled with CSS (fixed width), so if the total of widths doesn't match window size, the extra space is shown.

<img width="1527" alt="Screen Shot 2022-12-15 at 14 18 29" src="https://user-images.githubusercontent.com/16436160/207780202-f123a9ab-6f1c-4851-8e84-18f8c41e4d53.png">

## How

There would be some approaches to achieve the goal, so please choose one that you think is best.

**Comment by brc-dd** [comment]
This is already possible using styles:

```css
.table :deep(.col-name) { --table-col-max-width: auto; }
```

We have this present in our STable story too: https://github.com/globalbrain/sefirot/blob/main/stories/components/STable.story.vue#L202

**Comment by NozomuIkuta** [comment]
@brc-dd 

Setting `--table-col-max-width: auto;` would resolve first goal of this issue, wound't it?

How about second goal?
Does it also expand a column in the middle of the table?

**Comment by brc-dd** [comment]
Yeah, it works for middle columns too:

![image](https://user-images.githubusercontent.com/40380293/207841438-510601f6-764f-4169-8754-3198cf137048.png)

![image](https://user-images.githubusercontent.com/40380293/207841333-dc8e3858-9f94-4922-823e-6a6a3e1f0e8b.png)

**Comment by NozomuIkuta** [comment]
Hmm, @kiaking and @ryo-gk said that they had found edge case(s) in the past, where that approach doesn't work, but they seems to forget how to reproduce... 😅

**Comment by kiaking** [comment]
OK, I'm pretty sure there was an issue in certain cases. But no matter how I try I can't remember what it was... 😅 So, let's close this one for now... I'll post once I remember what it was 🤔
