### ISSUE TITLE
[Table] Error prop type on Cell component because of external type

### ISSUE THREAD

**Issue by kiaking** [globalbrain/sefirot#177]
We're getting this error.

```
[Vue warn]: Invalid prop: type check failed for prop "cell". Expected Null | Function, got Object  
  at <STableCell name="status" class-name=undefined cell= Object  ... > 
  at <STableItem key="status" name="status" class-name=undefined  ... > 
```

I think this is because we made changes in #174 and now `cell` props is defined as `TableCell | ((value: any, record: any) => TableCell)` which becomes `null | Function` because of current script setup limitation 😢 

I guess we need to redeclare TableCell type inside `STableCell` component.

**Comment by brc-dd** [comment]
Ah sorry about that. Warnings were disabled in my dev tools 😓. Redeclaring `TableCell` in the `STableCell` is not working too.

**Comment by kiaking** [comment]
Whaat... Hmmm... if here's no way to fix it, we might just define it as `any` then 😅
