### ISSUE TITLE
[Table] Add STableCellPills component

### ISSUE THREAD

**Issue by ryo-gk** [globalbrain/sefirot#178]
We need a STableCellPills component that accepts `string[]` as `value`, and show them as pills.
This is because the `STableCellPill` which we already have can't show multiple pills.

Design image is below. ("Topic type" column)
![image](https://user-images.githubusercontent.com/62658104/209038448-2fdba577-d0c8-46b8-abfe-48b2af253f32.png)

The usage is like below.

```ts
const table = useTable({
  ...
  columns: {
    tags: {
      label: 'Tags',
      cell: {
        type: 'pills',
        pills(items, record) {
          return items.map((item) => {
            return {
              label: item,
              color: item === 'info' ? 'info' : 'mute'
            }
          })
        }
      },
  },
  records: [
    { ... , tags: ['Info', 'News'], ... },
    { ... , tags: ['Info'], ... },
  ],
  ...
})
  ...
})
```

~Or, might be simpler to allow `STableCellPill` to accept also `string[]`?~

**Comment by kiaking** [comment]
> Or, might be simpler to allow STableCellPill to accept also string[]?

Yeah, it might 🤔 But however, I think we should make it accept an array of items and return pill objects so that we can have different colors depending on each value. This makes the API consistent with other type of cells.

So... maybe we should have a different API because the structure could be very different.

```ts
const table = useTable({
  ...
  columns: {
    tags: {
      label: 'Tags',
      cell: {
        type: 'pills',
        pills(items, record) {
          return items.map((item) => {
            return {
              label: item,
              color: item === 'info' ? 'info' : 'mute'
            }
          })
        }
      },
  },
  records: [
    { ... , tags: ['Info', 'News'], ... },
    { ... , tags: ['Info'], ... },
  ],
  ...
})
```

**Comment by ryo-gk** [comment]
> So... maybe we should have a different API because the structure could be very different.

I see, it looks good the API you suggested!
