### ISSUE TITLE
Make `SInputSelect` component test coverage 100%

### ISSUE THREAD

**Issue by kiaking** [globalbrain/sefirot#183]
I couldn't find out how to trigger `select` value change with Vue Test Utils. Tried `setValue` but couldn't make it work properly.

It would be cool if some one can tackle this 🤔  We need to test the `change` event on `select` component and see if component emits the correct value.

**Comment by brc-dd** [comment]
For me only this is working:

```ts
  test('check', async () => {
    const wrapper = mount(SInputSelect, {
      props: {
        options: [
          { label: 'First option', value: 1 }
        ]
      }
    })

    await wrapper.find('select').setValue(1)

    assertEmitted(wrapper, 'update:model-value', 1, '1')
    assertEmitted(wrapper, 'change', 1, '1')
  })
```

That too only when jsdom is set as the environment in vitest and the component is modified to set value as option.value instead of stringify(option). Also, the value being emitted in this case is a string. 🥲

**Comment by kiaking** [comment]
Ah... hmm... I did a similar thing but wasn't looking into jsdom and `encodeURIComponent` Good catch! It makes sense because it's not allowed to use funny characters in `<option value="">` attribute... 🤔?

Not sure why we must use JSDom... but I don't have any strong preference on using `happy-dom` either so that's OK too if we must change it.

Last thing, do you happen to know any way to emit the value from `<option>`. The only reason why I'm using `JSON.stringify` is to reserve type between `string`, `number`, and `boolean`.

```vue
<!--
  - The `select` is emitting the `change` event, and getting the
  - value from `e.target.value`, so if we don't JSON.stringify,
  - everything becomes a `string`.
  -->
<select
  class="select"
  :class="{ 'is-not-selected': isNotSelected }"
  :disabled="disabled"
  @focus="focus"
  @blur="blur"
  @change="emitChange"
>
  <option />
</select>
```

If we can emit the value as is, then we can avoid using JSON.stringify and might be able to solve this issue in more simple manner?

**Comment by brc-dd** [comment]
We can use index as option value? That works in happy-dom too. I'll create a PR.
