### ISSUE TITLE
Fix `SMarkdown` component showing vue-router warning on Histoire

### ISSUE THREAD

**Issue by kiaking** [globalbrain/sefirot#184]
When you access [SMarkdown component](https://story.sefirot.globalbrains.com/story/stories-components-smarkdown-01-playground-story-vue?variantId=_default) in Histoire, it shows the following warning.

```sh
[Vue warn]: injection "Symbol(router)" not found. 
  at <SMarkdown class="markdown" content="**We** shape our **buildings**. Thereafter, **they** shape **us**." > 
  at <RenderStorySubApp>
...
```

I think this is because `SMarkdown` uses `useRouter` under the hood, and we need to register `vue-router` to histoire setup 🤔

**Comment by cuebit** [comment]
Mocking `vue-router` globally will throw additional errors. It is advised that you should mock the router locally (1). Alternatively, we can universally access the router from within the component instance (2).

### 1. Mocking router per story

Add `setupApp?: (...args: any[]) => any` pass-through prop in `_support/Board.vue`.

In the story that requires router, add:
```vue
<script setup lang="ts">
import { Vue3StorySetupHandler } from '@histoire/plugin-vue'
import { createMemoryHistory, createRouter, routerKey } from 'vue-router'

const setupApp: Vue3StorySetupHandler = ({ app }) => {
  app.provide(routerKey, createRouter({
    history: createMemoryHistory(),
    routes: [{ path: '/', component: { render: () => null } }]
  }))
}
</script>

<template>
  <Board
    title="Components / SMarkdown / 01. Playground"
    :setup-app="setupApp"
  >
    ...
  </Board>
</template>
```

### 2. Universal access to router

Access router from the component instance, which negates the need to import `useRouter` altogether, and plays nicely with SSR.

```diff
 export function useLink({ container, callbacks }: UseLinkOptions): UseLink {
-  const router = useRouter()
+  const router = getRouter()
   ...
 }

+ function getRouter() {
+  return getCurrentInstance()?.proxy?.$router
+ }
```

**Comment by kiaking** [comment]
Thanks for the investigation! I like the first option better 👍 Maybe we could add `_support/Utils.ts` and create `setupVueRouter()` function or something like that for easier access?

**Comment by cuebit** [comment]
> Thanks for the investigation! I like the first option better 👍 Maybe we could add `_support/Utils.ts` and create `setupVueRouter()` function or something like that for easier access?

Great choice. I have done exactly that except I called the method setupApp with binding types. I think explicitness is key so I'll rename to `setupVueRouter` and we can pass that through assignment. 

Will publish and create PR 👍

**Comment by kiaking** [comment]
Thanks! And now that I think of it, maybe it should be `setupRouter` 😅
