### ISSUE TITLE
Make `support/Time` util test coverage 100%

### ISSUE THREAD

**Issue by kiaking** [globalbrain/sefirot#185]
I don't know why but it's showing that something is missing 🤔 

How can we make this pass?

<img width="643" alt="Screen Shot 2023-01-11 at 18 01 48" src="https://user-images.githubusercontent.com/3753672/211763083-f1f17c90-f892-4b92-916b-820dac0cda5b.png">

**Comment by cuebit** [comment]
exported members are treated as statements so would require an import somewhere. Since `sleep` is used in the same file, it'll need to be covered by a test. Alternatively, don't export.

Also, I noticed we can use the `Awaited` utility type. I'll create a separate issue for that.

**Comment by kiaking** [comment]
Ahh I thought we did. So we are simply missing the test 😅  OK, let's create test then 👍  PR welcome if anybody has time!

**Comment by cuebit** [comment]
I have a branch ready, just in case that was your preferred option 😅

Will publish and create PR 👍
