### ISSUE TITLE
Add "Addon Before" feature to `SInputText` and `SInputNumber`

### ISSUE THREAD

**Issue by kiaking** [globalbrain/sefirot#202]
design [Figma Design](https://www.figma.com/file/V9aRWurAXc6JggujTa2J4p/GB-Design-Kits?node-id=47%3A38&t=ou2UFLMkjDquZRi7-1)

The "Addon" is the feature where users can add an extra label or action button to the input.

<img width="272" alt="Screen Shot 2023-01-24 at 13 30 17" src="https://user-images.githubusercontent.com/3753672/214212435-4774e01c-773c-496c-93bf-57a1da3cffa3.png">

## Basics

Add `:addon-before` prop to `SInputText` and `SInputNumber` components. We add `-before` suffix because probably we want to have `:addon-after` in the future.

`:addon-before` can take a few types of value. `string`, `number`, or an icon. It should also have `addon-before-clickable` prop to make the addon act as a button.

```ts
import { IconifyIcon } from '@iconify/vue/dist/offline'

interface Props {
  // The label for the addon.
  addonBefore?: string | number | IconifyIcon

  // Whether the addon act as button. Defaults to `false`.
  addonBeforeClickable?: boolean
}
```

When `addonBeforeClickable` is true, it emits an event when the user clicks on it.

```ts
interface Emits {
  // Emits only when `Props.addonBeforeClickable === true`.
  (e: 'addon-before:click'): void
}
```

When adding this prop, it should display a component that looks 👇 

<img width="272" alt="Screen Shot 2023-01-24 at 13 30 17" src="https://user-images.githubusercontent.com/3753672/214213172-be3bec23-517f-4521-834e-67ded381e77f.png">

## Dropdown feature

Provide a way to add a dropdown feature to the addon as well. When this feature is enabled, users may click the addon, and display the `SDropdown` component as `SInputDropdown` does.

```ts
import { DropdownSectionFilter } from '@/composables/Dropdown'

interface Props {
  addonBefore?: string | number | IconifyIcon
  
  // Dropdown option same as `SInputDropdown`.
  addonBeforeDropdown?: AddonDropdownOption[]

  // Disable the dropdown search option. Defaults to `false`.
  addonBeforeDropdownNoSearch?: boolean

  // Whether to close the dialog when a user selects an item.
  // Defaults to `false`.
  addonBeforeDropdownCloseOnClick?: boolean
}

type AddonDropdownOption =
  | AddonDropdownOptionText
  | AddonDropdownOptionAvatar

interface AddonDropdownOptionBase {
  type?: 'text' | 'avatar'
  value: OptionValue
}

type AddonDropdownOptionValue = string | number | boolean

interface AddonDropdownOptionText extends AddonDropdownOptionBase {
  type?: 'text'
  label: string
}

interface AddonDropdownOptionAvatar extends AddonDropdownOptionBase {
  type: 'avatar'
  label: string
  image?: string | null
}
```

When dropdown is enabled, emit `addon-before:click` even when `addon-before-clickable` is not `true`. Also, emits additional events for dropdown item selection.

```ts
interface Emits {
  // Always emits when dropdown is enabled.
  (e: 'addon-before:click'): void

  // Emits when a user selects the item in dropdown.
  (e: 'addon-before:change', value: AddonDropdownOptionValue): void
}
```

When dropdown is enabled, it should show down caret after the addon label.

<img width="270" alt="Screen Shot 2023-01-24 at 13 37 36" src="https://user-images.githubusercontent.com/3753672/214215735-2985bc8c-7770-4d4b-a093-928fe8ec48a0.png">

## Disbale

The addon should check for `disabled` prop and if it's `true`, stop emitting any events. The design would should look like this.

<img width="284" alt="Screen Shot 2023-01-24 at 13 37 41" src="https://user-images.githubusercontent.com/3753672/214215843-a1e6ba8c-7398-44ad-b374-39d8d4b7df24.png">

## Light mode appearance

<img width="833" alt="Screen Shot 2023-01-24 at 13 37 59" src="https://user-images.githubusercontent.com/3753672/214213268-15be1a02-c913-4c9d-8e83-251d14687c1e.png">

**Comment by NozomuIkuta** [comment]
@kiaking 

I have 2 questions.

1. Just in case, it is intentional design that, while up and down arrows are shown in `SDropdown` and `SInputSelect` components, only up arrow is shown in `SInputAddon` component, isn't it?
2. How can I preview the light mode components in Figma? 🙏

**Comment by kiaking** [comment]
@NozomuIkuta

> Just in case, it is intentional design that, while up and down arrows are shown in SDropdown and SInputSelect components, only up arrow is shown in SInputAddon component, isn't it?

Good point! Wasn't thinking that much. But, I think we can go with only down caret. Because most of the time, value and the caret is going to be very close to each other. SInputSelect and SInputDropdown has more apparent carets because the carets are at very far right corner of the box 👍 

> How can I preview the light mode components in Figma?

You can't... it needs edit permission to switch. But don't worry too much since I'll adjust it in the end, and also it should work fine if you're using the right CSS variables 👍
