### ISSUE TITLE
Add `rows="fill"` option to `<SInputTextarea>`

### ISSUE THREAD

**Issue by kiaking** [globalbrain/sefirot#208]
It would be cool to have option that expands the whole textarea input to fill the height of the parent container. Currently, we can only specify exact rows.

Maybe this might be a bit challenging since we have label and help message wrapped by `<SInputBase>.` Maybe we need to apply flex or grid on `<SInputBase>`...?

## Props

```ts
interface Props {
  rows?: 'fill' | number
}
```

```html
<SInputTextare rows="fill" />
```

**Comment by brc-dd** [comment]
Can be hacked using a relative parent and absolute textarea: 👀 


https://user-images.githubusercontent.com/40380293/215522394-6ba1c671-7cba-478f-bff4-43efb2569a37.mov

**Comment by kiaking** [comment]
Wooow nice this is exactly what I want 🙌🙌🙌
