### ISSUE TITLE
Make `SInputYMD` / `SInputHMS` coverage 100%

### ISSUE THREAD

**Issue by kiaking** [globalbrain/sefirot#220]
It's almost there, but for some reason, I can't make `@blur` event to be covered 🤔  The function that's called by the blur event is covered.

<img width="504" alt="Screenshot 2023-02-09 at 16 54 02" src="https://user-images.githubusercontent.com/3753672/217751091-1c20f102-0933-484e-8985-fdba3704ddf2.png">

**Comment by brc-dd** [comment]
Closing this for now. The blur and focus related tests are already there, but c8 doesn't seem to pick them up as executed.
