### ISSUE TITLE
Make `SButtonGroup` coverage 100%

### ISSUE THREAD

**Issue by kiaking** [globalbrain/sefirot#223]
I have no idea how to make this 100% 😅 

<img width="476" alt="Screenshot 2023-02-15 at 16 36 04" src="https://user-images.githubusercontent.com/3753672/218967164-53b9f21a-96eb-4ae3-9adb-1a985e38df41.png">

**Comment by brc-dd** [comment]
This doesn't appear to be fixable. Tried with snapshotting as well as checking the class. But c8 doesn't seem to pick that up. Closing this for now.
