### ISSUE TITLE
[InputText] Display value overflow input box

### ISSUE THREAD

**Issue by kiaking** [globalbrain/sefirot#237]
Oh no 😅 

<img width="921" alt="Screenshot 2023-04-05 at 16 08 07" src="https://user-images.githubusercontent.com/3753672/230006567-2bd234a1-56e6-45fc-948b-5c5a400316d7.png">

The above error is happening with `SInputNumber`, but the underlining component is `SInputText`.

**Comment by brc-dd** [comment]
Not overflowing on histoire for me 👀 

How are you able to add commas though? For me it's just accepting numbers and changing them to scientific notation for large inputs 😅

<img width="330" alt="image" src="https://user-images.githubusercontent.com/40380293/230402318-ce254d75-76e0-4dc8-afd8-451d906e2db5.png">

**Comment by kiaking** [comment]
@brc-dd You can test it with.

```html
<SInputNumber separator :value="1000000 />
```

On `SInputText`, you need to be using `:displayValue` prop to reproduce this 😳  When `:displayValue` is set, the input will show the value when focus is out (this is where we insert commas. And that element is having trouble I think

**Comment by brc-dd** [comment]
Do we have to hide it or make it wrap/scroll?

**Comment by kiaking** [comment]
Good question. Let's hide it for now 👍
