### ISSUE TITLE
[Tooltip] Add "Click to activate" option

### ISSUE THREAD

**Issue by kiaking** [globalbrain/sefirot#256]
- ref #255 

Add option to show tooltip on click instead of hover. Maybe something like this?

```ts
interface Props {
  // Defaults to 'hover'.
  when?: 'click' | 'hover'

  // In ms. Close the tooltip after this time has passed.
  // Only relevant when `:when` is set to `'click'`.
  // Infinite if it's `undefined`.
  timeout?: number
}
```

```html
<STooltip when="click">
  ...
</STooltip>
```

**Comment by brc-dd** [comment]
The recommended way is to trigger it on both focus and hover and close on esc or pointer down 👀

https://zagjs.com/components/vue-sfc/tooltip
https://react-spectrum.adobe.com/react-aria/useTooltipTrigger.html

**Comment by kiaking** [comment]
Hmmm good point. Probably we should add that option too... Though that doesn't include optimization for touch device so I think we still need to activate it on tap as well 👀

**Comment by brc-dd** [comment]
Tap causes the element state to be focused right? So that should cover it IG.

**Comment by kiaking** [comment]
Oh, I didn't know that 😳 Nice then.
