### ISSUE TITLE
[Table] `TableColumn` properties should support reactive values

### ISSUE THREAD

**Issue by NozomuIkuta** [globalbrain/sefirot#275]
Currently, each property of `TableColumn` option only accepts nonreactive values on its initialization ([ref](https://github.com/globalbrain/sefirot/blob/95d2d34f5aa6e725fec11e43d88e7183f2d0901c/lib/composables/Table.ts#L37C18-L45)).

It should accept reactive values so that we can dynamically change table's appearance (e.g. i18n support for `label` and text in dropdown).

**Comment by kiaking** [comment]
Good point, but not sure if want to make all the nested properties reactive. We can always use ref at the top level.

```ts
export interface Table<
  O extends string = any,
  R extends Record<string, any> = any,
  SR extends Record<string, any> = any
> {
  orders: MaybeRef<O[]>
  columns: MaybeRef<TableColumns<O, R, SR>> // <- !!!
  records?: MaybeRef<R[] | null | undefined>
  header?: MaybeRef<boolean | undefined>
  footer?: MaybeRef<boolean | undefined>
  summary?: MaybeRef<SR | null | undefined>
  total?: MaybeRef<number | null | undefined>
  page?: MaybeRef<number | null | undefined>
  perPage?: MaybeRef<number | null | undefined>
  reset?: MaybeRef<boolean | undefined>
  borderless?: MaybeRef<boolean>
  loading?: MaybeRef<boolean | undefined>
  virtualScroll?: MaybeRef<boolean | undefined>
  onPrev?(): void
  onNext?(): void
  onReset?(): void
}
```

To make things simple, unless we get some performance issues, I would say we can live with just passing ref from the root 🤔 

```ts
useTable({
  ...
  columns: computed(() => ({
    ...
  }))
})
```

**Comment by kiaking** [comment]
Closing this for now. While this might be nice to have, there is trade off with complicity and we don't have solid conclusion on whether we want to do this.

If we find a good use case for this feature, let's open up another issue on that time.
