### ISSUE TITLE
[Dropdown] Pass props to and listen to events from component

### ISSUE THREAD

**Issue by NozomuIkuta** [globalbrain/sefirot#308]
With current Dropdown section of type `component`, we can't pass props to the component and listen event from it (e.g. implementing `v-model` to it).

By supporting this feature, we can implement more dynamic and flexible component in dropdown like form items.

Note: it seems that `TableCellComponent` supports this feature.

**Comment by kiaking** [comment]
For the event, I think we don't need special care for this. We can pass callback to props and that's what we usually do in other components where we pass options as object 👀 

```ts
const dropdown = {
  ...
  props: {
    onClick: () => doSomeThing()
  }
}
```

**Comment by cuebit** [comment]
I do prefer render functions. It's easier to pass props and, quite rightly mentioned, main type safety.

Also reduces the complexity of having deeply nested objects and/or identity functions for passive props. 🫡
