### ISSUE TITLE
[Table] Unexpected horizontal scroll on dropdown when item text is too long

### ISSUE THREAD

**Issue by kiaking** [globalbrain/sefirot#319]
We get this horizontal scroll effect.

<img width="268" alt="Screenshot 2023-07-20 at 15 55 49" src="https://github.com/globalbrain/sefirot/assets/3753672/8040e0be-f0d1-45fd-8a71-45864eeeb5a4">

This only happens on `<STable>`. If we use `<SDropdown>` or `<SInputDropdown>`, the long text gets wrapped. It should behave the same for table too.

**Comment by brc-dd** [comment]
Any idea why this was added?

https://github.com/globalbrain/sefirot/blob/adbe8754c38b9e327b143839138e94f0cf50351a/lib/components/STable.vue#L390

Removing/reseting it would fix this.

**Comment by kiaking** [comment]
Hmmm that is added for `.table` class so probably for table's horizontal scrolling...? But why is that style leaking into dropdown 🤔 ?

Though, without looking into the details, if removing that wouldn't break table's horizontal scroll feature, I think we can remove that one 👍
