### ISSUE TITLE
[Grid] Styles not able to override with CSS

### ISSUE THREAD

**Issue by kiaking** [globalbrain/sefirot#321]
We should be able to define `SGrid` component style by using `grid-template-column` and `gap` but this is not possible now due to inline styling.

When props are not defined, it should not define the inline style.

```ts
// SGrid

const styles = computed(() => {
  // Oh no... It should be undefined instead of having default values.
  return {
    gridTemplateColumns: `repeat(${props.cols ?? 1}, minmax(0, 1fr))`,
    gap: `${props.gap ?? 0}px`
  }
})
```

**Comment by brc-dd** [comment]
we can probably refactor it to v-bind in css, that way it will be overridable by other styles. wdyt?

**Comment by kiaking** [comment]
Oh yeah we can do that! 👍
