### ISSUE TITLE
[Input] Enable font family customization

### ISSUE THREAD

**Issue by kiaking** [globalbrain/sefirot#322]
Let's add a new input related CSS variable (`--input-value-font-family`) that can adjust font family.

This is useful when we want to have mono spaced font family on textarea when we expect user to input for example JSON value.

**Comment by cuebit** [comment]
@kiaking is this only applicable to `SInputTextarea` at this point in time?

**Comment by kiaking** [comment]
I think we can apply this to others which have text input such as `SInputText`, `SInputNumber`, `SInputDropdown` 👀

**Comment by cuebit** [comment]
How do you want to handle inputs that use `--font-family-number`? Are these left unchanged?

**Comment by kiaking** [comment]
Let's make `--font-family-number` default but overridable via `--input-value-font-family` 👍 

```css
font-family: var(--input-value-font-family, --font-family-number);
```

**Comment by cuebit** [comment]
Gotcha. In this case, we cannot set a default value for `--input-value-font-family` in variables.css, that's intended correct?

**Comment by kiaking** [comment]
Yes! We do have a few such variables. Like `--button-padding` where it only appears at `SButton` and not in `variables.css`.
https://sefirot.globalbrains.com/components/button#styles
