### ISSUE TITLE
[Input] The label font size is not correct

### ISSUE THREAD

**Issue by kiaking** [globalbrain/sefirot#350]
Seems like label font size is using the default value now but it should be `14px`. It's working fine on Histoire because it has font size 14px set globally for styling purpose but usually we have 16px as default on other projects, hence we should have explicit style for input label I guess.

Maybe we should add [Shared Input Styles](https://sefirot.globalbrains.com/styles/input-styles) for `--input-label-font-size: 14px` 👀 

<img width="600" alt="Screenshot 2023-10-03 at 13 50 55" src="https://github.com/globalbrain/sefirot/assets/3753672/bcc6d702-2590-4512-aa04-2649cdf89646">

**Comment by brc-dd** [comment]
Ah, actually classes are wrong in SInputBase styles.
