### ISSUE TITLE
[Table] Set actions column/cell width automatically

### ISSUE THREAD

**Issue by kiaking** [globalbrain/sefirot#377]
The width of table's actions cell can be determined by how many actions there are, so it would be cool if we can do that. A bit tricky since we need to set width for both column and cell.

The rule is this.

1. A button have width of `28px`.
2. There are no gap between buttons.
3. There should be `8px` padding left and right inside cell.

So, if we have 3 buttons, the width of the cell should be:

```ts
(button width 28px * 3) + (padding left 8px + padding right 8px) = 100px
```

When there are no buttons, set width to 40px. Which makes the cell square.

<img width="1290" alt="Screenshot 2023-11-13 at 16 24 12" src="https://github.com/globalbrain/sefirot/assets/3753672/a91ab986-42ee-4a1f-b191-19abf9ff0fc0">

**Comment by brc-dd** [comment]
A fixed formula might cause issues if the icon is not square or if label is specified 👀

**Comment by kiaking** [comment]
@brc-dd
Wasn't thinking about icon having different size honestly, but, for the label you are absolutely right...!

Maybe only do this when all buttons have no label? 🤔

Or... should we go more wild and check for the final cell width and apply it to column...? In this case, we set padding 8px in actions cell by default 👀

**Comment by brc-dd** [comment]
If we assume that icons are always square, then I guess it can be done without having to check the DOM width. I guess phosphor doesn't have non-square icons. So we should be good unless we are passing some custom component.
