### ISSUE TITLE
[Url] Support `MaybeRef` on `useUrlQuerySync`

### ISSUE THREAD

**Issue by kiaking** [globalbrain/sefirot#429]
Currently, `useUrlQuerySync` only accept reactive object as a state, but would be cool if we can pass in `MaybeRefOrGetter`.

**Comment by brc-dd** [comment]
We need to assign values to the state too. Getters won't work.

**Comment by kiaking** [comment]
Ah, good point. Then not getter but only `MaybeRef` 👍
