### ISSUE TITLE
[Validation] Allow rule only field

### ISSUE THREAD

**Issue by kiaking** [globalbrain/sefirot#447]
Currently, `useV` can only define keys that exist in the given data. But there are cases where having virtual field only for validation makes sense. Can we make this possible?

```ts
const { data } = useD({
  firstName: '',
  lastName: ''
})

const { validation } = useV(data, {
  // This gives type error right now.
  fullName: {
    require: rule(() => {
      return data.value.firstName && data.value.lastName
    })
  }
})
```

**Comment by brc-dd** [comment]
Bit tricky without casting. Maybe just set `fullName: undefined` in useD call 👀

**Comment by kiaking** [comment]
Hmmm yeah make sense 👀 Let's go with that 👍
