### ISSUE TITLE
rfc: Alert modal composition

### ISSUE THREAD

**Issue by cuebit** [globalbrain/sefirot#47]
# Summary

Currently the `useAlert` composable allows only type-hinting.

However, it can be improved to also handle operations such as open/close _out of the box_.

# Motivation

* Remove the mundane task of generating store action callbacks.
* Promotes the use of `'alert/close'` instead of `'modal/close'` actions.
* Makes the composition more functional amidst basic data handling.

# Basic example

## Before

```ts
const data = useAlert({
  type: 'danger',
  title: 'Delete me',
  text: 'This action cannot be undone. You have been warned.',
  actions: [
    useButtonAction({
      kind: 'primary',
      mode: 'danger',
      label: 'DELETE',
      callback: () => {
        await regretfulAction()
        close()
      }
    }),
    useButtonAction({
      kind: 'mute',
      mode: 'neutral',
      label: 'CANCEL',
      callback: () => close()
    })
  ]
})

function open() {
  store.dispatch('alert/open', data)
}

function close() {
  store.dispatch('alert/close')
}

open()
```

## After

```ts
const { open, close } = useAlert({
  type: 'danger',
  title: 'Delete me',
  text: 'This action cannot be undone. You have been warned.',
  actions: [
    useButtonAction({
      kind: 'primary',
      mode: 'danger',
      label: 'DELETE',
      callback: () => {
        await regretfulAction()
        close()
      }
    }),
    useButtonAction({
      kind: 'mute',
      mode: 'neutral',
      label: 'CANCEL',
      callback: () => close()
    })
  ]
})

open()
```

**Comment by kiaking** [comment]
Nice! I like the overall idea 👍 👍 👍

**Comment by cuebit** [comment]
Rumour has it, you're looking to refactor the alert modals and such. Will this impact that in any way?

**Comment by kiaking** [comment]
Nope. I think `useButtonAction` will be more simplified to be `useAction` or something. But overall api wouldn't have any effect!
