### ISSUE TITLE
[Avatar] Image is not filled when aspect ratio is not 1:1

### ISSUE THREAD

**Issue by kiaking** [globalbrain/sefirot#479]
Do `object-fit: cover`.

<img width="192" alt="Screenshot 2024-02-22 at 12 46 25" src="https://github.com/globalbrain/sefirot/assets/3753672/b5e7fa5f-6e07-4180-9382-90d108cdfa14">

**Comment by brc-dd** [comment]
This seems to be already fixed?

**Comment by kiaking** [comment]
Oh really...? I don't remember touching it so, not sure 🤔 Need to test 👀

**Comment by brc-dd** [comment]
Ok, wait no. My image was wrong.
