### ISSUE TITLE
[Avatar] Support multiple avatars

### ISSUE THREAD

**Issue by NozomuIkuta** [globalbrain/sefirot#484]
While `STableCellAvatars` exists for `STableCellAvatar`, there is no corresponding component for `SAvatar`.
I found there is a case where multiple `SAvatar`s are shown outside the table.

**Comment by kiaking** [comment]
Yeah I was thinking of this too. Probably `<SAvatarStack>` like GitHub Primer.
https://primer.style/components/avatar-stack/
