### ISSUE TITLE
Helpers section for docs

### ISSUE THREAD

**Issue by cuebit** [globalbrain/sefirot#62]
For the sake of simplicity, not necessity, it may be worth considering having a section (e.g. Helpers) to provide a brief explanation and outline functionality of composition helpers (e.g. `useStore`, `useRouter`, `useAlert`, `useValidation`, etc).

This would provide more coverage for hidden gems in a composition environment that may otherwise go unnoticed. It may even be helpful to contributors without having to delve too much into the source code.

**Comment by kiaking** [comment]
Yes! We should! I think the menu should be named "Composables"?

**Comment by cuebit** [comment]
Yep, I think it just about fits before the breakpoint hits 😄

**Comment by kiaking** [comment]
Oh haha
