### ISSUE TITLE
select component style question

### ISSUE THREAD

**Issue by lvfangren** [globalbrain/sefirot#83]
The style of the select component drop-down menu seen in the document is very strange。
1: The drop-down menu obscures the display box
2:The drop-down menu style 。。。。
 
info: 
OS/Browsers version
MacBook Pro (13-inch, M1, 2020)

Steps to reproduce
click select and show drop-down menu 

What is Expected
like Dropdown component drop-down menu style or other

**Comment by kiaking** [comment]
Hi! Thanks for the report. What do you mean by strange? Could you elaborate a bit more. It looks to me it's expected 👀

**Comment by kiaking** [comment]
Ah, OK I see. Well, `SInputSelect` is meant be native `select`, which browser provides. Where SInputDropdown is Sefirot designed version.

Usually, if the list of items are small, native select box gives better user experience especially on mobile. If you want Dropdown style, please use SInputDropdown 👍

**Comment by lvfangren** [comment]
modals-alert component click button and pop up dialogue， try click enter dialogue no close, and try click DISMISS or 
CLOSE ALERT dialogue no close
